## Understand the Dataset

In [1]:
# Import Libraries
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# Read the data from https://github.com/tantikristanti/Datasets/
prefix = 'https://github.com/tantikristanti/Datasets/releases/download/v1.0.0-yellow-alpha'
file_name = 'yellow_tripdata_2026-01.csv.gz'
url = f'{prefix}/{file_name}'
df_01_2026 = pd.read_csv(url)

/var/folders/w8/kytqh_fs0nlg915bn2gl3kkc0000gn/T/ipykernel_21011/677109421.py:5: DtypeWarning: Columns (0: store_and_fwd_flag) have mixed types. Specify dtype option on import or set low_memory=False.
  df_01_2026 = pd.read_csv(url)

In [3]:
df_01_2026.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-01-01 00:54:04.000000,2026-01-01 00:59:37.000000,1.0,0.97,1.0,N,239,238,1,7.2,1.00,0.5,3.66,0.0,1.0,15.86,2.5,0.0,0.00
1,1,2026-01-01 00:34:04.000000,2026-01-01 00:39:47.000000,0.0,0.90,1.0,N,163,162,2,7.9,4.25,0.5,0.00,0.0,1.0,13.65,2.5,0.0,0.75
2,1,2026-01-01 00:57:06.000000,2026-01-01 01:05:59.000000,0.0,1.40,1.0,N,43,237,1,10.7,4.25,0.5,2.50,0.0,1.0,18.95,2.5,0.0,0.75
3,2,2026-01-01 00:15:22.000000,2026-01-01 00:58:10.000000,4.0,5.58,1.0,N,142,209,1,38.7,1.00,0.5,11.11,0.0,1.0,55.56,2.5,0.0,0.75
4,2,2026-01-01 00:27:13.000000,2026-01-01 00:40:43.000000,0.0,2.16,1.0,N,88,144,1,13.5,1.00,0.5,3.85,0.0,1.0,23.10,2.5,0.0,0.75

In [4]:
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

In [5]:
# Read the CSV data in batches. The size of each batch is, for example, 100000
df_01_2026_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000 # Size of each batch; it can be adjusted based on the available memory and performance requirements.
)

In [6]:
df_next = next(df_01_2026_iter)

In [7]:
df_next

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1,0.97,1,N,239,238,1,7.2,1.00,0.5,3.66,0.00,1.0,15.86,2.5,0.00,0.00
1,1,2026-01-01 00:34:04,2026-01-01 00:39:47,0,0.90,1,N,163,162,2,7.9,4.25,0.5,0.00,0.00,1.0,13.65,2.5,0.00,0.75
2,1,2026-01-01 00:57:06,2026-01-01 01:05:59,0,1.40,1,N,43,237,1,10.7,4.25,0.5,2.50,0.00,1.0,18.95,2.5,0.00,0.75
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4,5.58,1,N,142,209,1,38.7,1.00,0.5,11.11,0.00,1.0,55.56,2.5,0.00,0.75
4,2,2026-01-01 00:27:13,2026-01-01 00:40:43,0,2.16,1,N,88,144,1,13.5,1.00,0.5,3.85,0.00,1.0,23.10,2.5,0.00,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2,2026-01-02 14:02:58,2026-01-02 14:03:07,2,0.01,2,N,107,107,1,70.0,0.00,0.5,10.00,6.94,1.0,91.69,2.5,0.00,0.75
99996,2,2026-01-02 14:36:46,2026-01-02 15:20:02,2,16.78,1,N,138,48,1,69.5,5.00,0.5,17.24,6.94,1.0,105.18,2.5,1.75,0.75
99997,2,2026-01-02 14:47:47,2026-01-02 15:08:07,1,6.07,1,N,170,13,1,28.9,0.00,0.5,6.73,0.00,1.0,40.38,2.5,0.00,0.75
99998,2,2026-01-02 14:21:58,2026-01-02 14:28:20,1,1.12,1,N,162,141,1,7.9,0.00,0.5,2.53,0.00,1.0,15.18,2.5,0.00,0.75
99999,2,2026-01-02 14:44:38,2026-01-02 14:48:53,1,0.32,1,N,237,162,4,-5.8,0.00,-0.5,0.00,0.00,-1.0,-10.55,-2.5,0.00,-0.75